import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {BatteryQueue} from '../battery/queue.mjs';
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'battery-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));let state={modelReady:true,hasTask:false};const calls=[];
const a={jobs:async()=>['job'],observe:async()=>({...state}),validate:async()=>{},capacity:async()=>true,post:async()=>{calls.push('post');state.hasTask=true;},execute:async()=>{calls.push('execute');state.settled=true;},settle:async()=>{},archive:async()=>{calls.push('archive');return 'hash';},deliver:async()=>{calls.push('deliver');state.closed=true;state.delivered=true;}};
return {a,dir,state,calls,q:new BatteryQueue(a,dir),status:()=>JSON.parse(fs.readFileSync(path.join(dir,'job.json'))).status};}
test('restart after mined post does not pay again, and archive precedes delivery',async t=>{const f=fixture(t);await f.q.tick();f.q=new BatteryQueue(f.a,f.dir);await f.q.tick();f.state.final=true;f.state.accepted=true;await f.q.tick();await f.q.tick();assert.deepEqual(f.calls,['post','execute','archive','deliver']);assert.equal(f.status(),'delivered');});
test('unknown broadcast response reconciles with the mined task',async t=>{const f=fixture(t);f.a.post=async()=>{f.calls.push('post');f.state.hasTask=true;throw Error('connection lost');};await f.q.tick();await f.q.tick();assert.deepEqual(f.calls,['post','execute']);});
test('no model, capacity, or budget means no spending',async t=>{const f=fixture(t);f.state.modelReady=false;await f.q.tick();assert.equal(f.status(),'waiting_model');f.state.modelReady=true;f.a.capacity=async()=>false;await f.q.tick();assert.equal(f.status(),'waiting_capacity');f.state.expired=true;await f.q.tick();assert.equal(f.status(),'refund_available');assert.equal(f.calls.length,0);});
test('disputes, challenge windows and archive failures cannot become delivery',async t=>{const f=fixture(t);Object.assign(f.state,{hasTask:true,disputed:true});await f.q.tick();assert.equal(f.status(),'in_dispute');Object.assign(f.state,{disputed:false,settled:true});await f.q.tick();assert.equal(f.status(),'awaiting_finality');Object.assign(f.state,{final:true,accepted:true});f.a.archive=async()=>{throw Error('incorrect execution root');};await f.q.tick();assert.equal(f.status(),'needs_attention');assert.equal(f.calls.length,0);});
