import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { parseEther } from 'viem';
import * as H from './harness.mjs';
import { enrollmentMetadata } from '../relayer/enrollment.mjs';

H.forgeBuild();
const anvil = await H.startAnvil(8588), running = [];
const waitFor = async (fn) => { for (let n=0;n<100;n++) { if (await fn()) return; await H.sleep(150); } throw Error('relayer condition timed out'); };
try {
 const dep=await H.deployMesh(anvil.rpc), admin=H.clientsFor(dep,H.KEYS[0]);
 const base=await H.registerSyntheticMep(dep,H.KEYS[0],{name:'base-pool'});
 const legacySelectors=H.clientsFor({...dep,addresses:{...dep.addresses,meps:dep.addresses.verifier,instances:dep.addresses.verifier}},H.KEYS[0]);
 assert.deepEqual(await enrollmentMetadata(legacySelectors,base.mepId),{baseMepId:null,enrollmentMepId:base.mepId},'actual empty EVM selector reverts preserve legacy behavior');
 const child=await H.syntheticMep({name:'derived-pool'});
 const {withBase,withTerms}=await H.porw('mep.js');
 const mepId=H.hex(withTerms(withBase(child.mep,base.mepId),admin.account.address,500).mepId);
 await H.sendTo(admin,dep.addresses.meps,'MEPRegistry','registerDerivedMEPWithTerms',[child.fields,base.mepId,admin.account.address,500]);
 const legacy=await H.startRelayer(dep,H.KEYS[3],[mepId],{env:{PORW_BEACON_LAZY:'1'}});running.push(legacy);
 const legacyRows=await legacy.api('/meps');
 assert.equal(legacyRows.length,1);assert.equal(legacyRows[0].baseMepId,base.mepId);assert.equal(legacyRows[0].enrollmentMepId,mepId);
 legacy.stop();await new Promise(resolve=>legacy.child.once('exit',resolve));
 await H.sendTo(admin,dep.addresses.instances,'InstanceRegistry','setMEPRegistry',[dep.addresses.meps]);
 const R=await H.startRelayer(dep,H.KEYS[3],[mepId],{env:{PORW_BEACON_LAZY:'1',PORW_BEACON_WAKE_EPOCHS:'2'}});running.push(R);
 const rows=await R.api('/meps');assert.equal(rows.length,2);
 const entry=rows.find(x=>x.mepId===mepId);assert.equal(entry.baseMepId,base.mepId);assert.equal(entry.enrollmentMepId,base.mepId);assert.equal(entry.royaltyBps,500);
 assert.equal(rows.find(x=>x.mepId===base.mepId).baseMepId,null);
 const host=H.clientsFor(dep,H.KEYS[1]);
 await host.pub.waitForTransactionReceipt({hash:await host.instances.write.bond([[base.mepId]],{value:parseEther('0.5')})});
 await waitFor(async()=>Number((await R.api('/status')).block)>0);
 assert.equal((await R.api('/wake',{instance:host.account.address})).ok,true);
 const toBlock=async block=>{const current=await anvil.block();if(block>current)await anvil.mine(block-current);};
 const epoch=Math.floor((await anvil.block())/40)+1;
 await toBlock(epoch*40-5);await waitFor(async()=>(await R.api('/status')).commits.includes(epoch));
 await toBlock(epoch*40+2);await waitFor(async()=>(await R.api('/status')).reveals.includes(epoch));
 await toBlock(epoch*40+12);await waitFor(async()=>(await R.api('/status')).epochsRolled.includes(epoch));
 await waitFor(async()=>(await R.api('/status')).aggregators.find(x=>x.mep===base.mepId)?.epochs.some(x=>x.epoch===epoch));
 const status=await R.api('/status');assert.equal(status.aggregators.find(x=>x.mep===mepId).epochs.length,0);
 const ep=await R.api('/epoch?mep='+base.mepId), childEp=await R.api('/epoch?mep='+mepId);
 assert.equal(childEp.mepId,mepId);assert.equal(childEp.enrollmentMepId,base.mepId);assert.notEqual(childEp.challenge,ep.challenge);
 const {PorwNode}=await H.porw('node.js'),{loadKernelFromBytes}=await H.porw('porw.js');
 const {RelayClient}=await H.porw('relay_client.js'),{NodeService}=await H.porw('node_service.js');
 const domains=(await R.api('/deployment')).domains;
 const node=new PorwNode(await loadKernelFromBytes(fs.readFileSync(path.join(H.porwDir,'sketch.wasm'))),{privHex:H.KEYS[1],domains});
 await node.loadModel('base-pool',base.payload,{maxSteps:base.steps});
 const relay=new RelayClient([R.relay],node.key);await relay.connect();running.push({stop:()=>relay.close()});
 const service=new NodeService(node,relay,{});service.serve(base.mep.mepId);await service.announce(base.mep.mepId,H.unhex(ep.challenge));
 await waitFor(async()=>(await R.api('/status')).aggregators.find(x=>x.mep===base.mepId).epochs.some(x=>x.epoch===epoch&&x.claims===1));
 // Skip the next reveal entirely: closing base claims must work even in a cold epoch.
 await toBlock((epoch+1)*40+12);
 await waitFor(async()=>(await R.api('/status')).rootsPosted.some(x=>x.epoch===epoch&&x.count===1));
 const proof=await R.api(`/proof?mep=${base.mepId}&epoch=${epoch}&instance=${host.account.address}`);assert(proof.posted);
 assert.equal((await R.api(`/proof?mep=${mepId}&epoch=${epoch}&instance=${host.account.address}`)).error?.startsWith('no proof'),true);
 assert.equal((await R.api('/tx/materialize',{mep:base.mepId,epoch,instance:host.account.address})).ok,true);
 assert.equal(await host.instances.read.isEligible([host.account.address,mepId,BigInt(epoch+1)]),true);
 const hosts=await R.api('/hosts?instance='+host.account.address);assert(hosts.eligibleModels.includes(mepId));assert(hosts.eligibleModels.includes(base.mepId));
 assert.equal((await R.api('/status')).errors.length,0);
 console.log('base relayer: configured/unconfigured routing, child metadata, base-only cold-epoch proof and child eligibility passed');
} finally {for(const process of running)process.stop();anvil.stop();}
process.exit(0);
