import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { startFrontend } from '../frontend/serve.mjs';
const server=await startFrontend(0);
const browser=await chromium.launch({headless:true,...(process.env.PW_CHROMIUM?{executablePath:process.env.PW_CHROMIUM}:{})});
try {
 const page=await browser.newPage({reducedMotion:'reduce'});
 let holders=[{address:'0x'+'a'.repeat(40),tokens:Array.from({length:200},(_,i)=>i+1)}];
 await page.route('**/flybnb/holders',route=>route.fulfill({json:{block:123,totalSupply:200,holders}}));
 await page.goto(server.url);await page.waitForFunction(()=>window.__ready);
 await page.evaluate(()=>{
  const s=window.app.state;
  s.meps=Array.from({length:200},(_,i)=>({mepId:'0x'+(i+1).toString(16).padStart(64,'0'),modelId:'0x'+(i+1).toString(16).padStart(64,'0'),name:`fly ${i+1}`,neurons:100,synapses:1000,exec:'int-lif',weightsDA:'https://example.invalid/model.bin',providers:0}));
  window.appActions.setActive(s.meps[0].mepId);
 });
 await page.locator('.main.stay .brain').first().waitFor();
 assert.equal(await page.locator('.brain').count(),12,'only current route page should mount cards');
 await page.locator('#brainsNext').click();
 assert.equal(await page.locator('#brainsCatalog .brain .name').first().innerText(),'fly 13\nINT-LIF');
 await page.locator('#brainsSearch').fill('fly 200');
 assert.equal(await page.locator('#brainsCatalog .brain').count(),1);
 await page.click('#navHost'); await page.locator('#hostCatalog').waitFor();
 assert.equal(await page.locator('.brain').count(),12);
 await page.locator('#hostNext').click();
 await page.locator('#hostCatalog .brain input').first().check();
 await page.locator('#hostScope').selectOption('selected');
 assert.equal(await page.locator('#hostCatalog .brain').count(),1,'selection survives pagination');
 await page.click('#navDocs'); await page.waitForFunction(()=>!document.getElementById('hostCatalog'));assert.equal(await page.locator('.brain').count(),0);
 assert.equal(await page.locator('#steps').count(),1,'background node controls remain mounted');
 await page.click('#navFlyBnb');await page.locator('#flybnbHoldersSummary').waitFor();
 assert.equal(await page.locator('.brain').count(),0);
 assert.equal(await page.locator('#flybnbHolders .toks').count(),0,'token IDs should not mount before expansion');
 await page.locator('#flybnbHolders summary').click(); await page.locator('#flybnbHolders .toks').waitFor();
 assert.equal(await page.locator('#flybnbHolders .toks').count(),1);
 assert.match(await page.locator('#flybnbHolders .toks').innerText(),/#200/);
 holders=Array.from({length:25},(_,i)=>({address:'0x'+(i+1).toString(16).padStart(40,'0'),tokens:[i+1]}));
 await page.click('#navDocs');await page.locator('#flybnb').waitFor({state:'detached'});
 await page.click('#navFlyBnb');await page.locator('#flybnbHolders li').first().waitFor();
 assert.equal(await page.locator('#flybnbHolders li').count(),12);
 await page.locator('#flybnb').getByRole('button',{name:'Next',exact:true}).click();
 await page.locator('#flybnb').getByRole('button',{name:'Next',exact:true}).click();
 assert.equal(await page.locator('#flybnbHolders li').count(),1);
 assert.match(await page.locator('#flybnb').innerText(),/Page 3 of 3/);
 await page.click('#navStay'); await page.locator('#brainsCatalog').waitFor();
 await page.locator('#brainsSearch').fill('');
 await page.screenshot({path:'/tmp/catalog-paged-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'mobile catalog should fit viewport');
 await page.screenshot({path:'/tmp/catalog-paged-mobile.png',fullPage:true});
 console.log('catalog pages: route isolation, 12-card pages, search, selection and compact acknowledgments passed');
} finally {await browser.close();server.server.close();}
