import test from 'node:test';
import assert from 'node:assert/strict';
import { saveBrowserCapacity } from '../frontend/src/core/host-capacity.js';
const wallet='0x'+'11'.repeat(20),market='0x'+'22'.repeat(20),registry='0x'+'33'.repeat(20);
function fixture(){const sent=[];const C={state:{wallet,chainOk:true,deployment:{chainId:97,addresses:{market}},node:{models:new Map([['m',{}]]),identity:{instance:wallet,chainId:97,market}}},call:async()=> '0x'+registry.slice(2).padStart(64,'0'),send:async(...args)=>{sent.push(args);return {status:'0x1'};}};return {C,sent,snapshot:{enabled:true,authorized:true,registry,market,instance:wallet,chainId:97}};}
test('browser advertises at most its single serial executor; pause needs no running node',async()=>{const {C,sent,snapshot}=fixture();await saveBrowserCapacity(C,snapshot,1);assert.deepEqual(sent[0],[registry,'setCapacity(uint16)',[1]]);C.state.node=null;await saveBrowserCapacity(C,snapshot,0);assert.equal(sent.length,2);await assert.rejects(saveBrowserCapacity(C,snapshot,2),/serial/);await assert.rejects(saveBrowserCapacity(C,snapshot,1),/Start/);});
test('reject stale wallet, chain, market, disabled capability and changed registry before signing',async()=>{for(const mutate of [c=>c.state.wallet=registry,c=>c.state.chainOk=false,c=>c.state.deployment.chainId=56,c=>c.state.deployment.addresses.market=registry,c=>c.call=async()=> '0x'+'00'.repeat(32)]){const {C,sent,snapshot}=fixture();mutate(C);await assert.rejects(saveBrowserCapacity(C,snapshot,1));assert.equal(sent.length,0);}const {C,snapshot}=fixture();await assert.rejects(saveBrowserCapacity(C,{...snapshot,enabled:false},1));await assert.rejects(saveBrowserCapacity(C,{...snapshot,authorized:false},1));});
test('wallet switch during chain verification and reverted writes fail',async()=>{const {C,sent,snapshot}=fixture();C.call=async()=>{C.state.wallet=registry;return '0x'+registry.slice(2).padStart(64,'0');};await assert.rejects(saveBrowserCapacity(C,snapshot,1));assert.equal(sent.length,0);const f=fixture();f.C.send=async()=>({status:'0x0'});await assert.rejects(saveBrowserCapacity(f.C,f.snapshot,1),/reverted/);});

test('a running node for another wallet or deployment cannot resume the current wallet',async()=>{for(const identity of [{instance:registry,chainId:97,market},{instance:wallet,chainId:56,market},{instance:wallet,chainId:97,market:registry},null]){const {C,sent,snapshot}=fixture();C.state.node.identity=identity;await assert.rejects(saveBrowserCapacity(C,snapshot,1),/running host/);assert.equal(sent.length,0);await saveBrowserCapacity(C,snapshot,0);assert.equal(sent.length,1);}});
test('round browser capacity is explicitly selected and bounded by the advertised round limit',async()=>{const {C,snapshot,sent}=fixture();C.state.deployment.verification={mode:'synchronous-vrf-rounds-v1',maxRoundTasks:4};await saveBrowserCapacity(C,snapshot,2);assert.deepEqual(sent[0][2],[2]);await assert.rejects(saveBrowserCapacity(C,snapshot,5),/capacity|limit/);await assert.rejects(saveBrowserCapacity(C,snapshot,1.5));});
