import test from 'node:test';
import assert from 'node:assert/strict';
import { capacityReader } from '../relayer/capacity.mjs';
const market='0x'+'11'.repeat(20), registry='0x'+'22'.repeat(20), host='0x'+'33'.repeat(20), zero='0x'+'00'.repeat(20);
function fixture(){let calls=[];let fail=false;const pub={readContract:async c=>{calls.push(c.functionName);if(fail)throw Error('RPC quota');return {hostCapacity:registry,snapshot:[10,2,8],authorizedMarkets:true}[c.functionName];}};return {pub,calls,fail:()=>{fail=true;},recover:()=>{fail=false;}};}
test('capacity is shared, cached and concurrent requests coalesce',async()=>{const f=fixture(),r=capacityReader(f.pub,market);const a=await Promise.all([r(host),r(host)]);assert.deepEqual(a[0],{enabled:true,registry,market,instance:host,authorized:true,limit:10,active:2,free:8});assert.deepEqual(a[0],a[1]);assert.equal(f.calls.filter(x=>x==='snapshot').length,1);await r(host);assert.equal(f.calls.length,3);});
test('legacy getter absence and unset wiring disable only capacity',async()=>{for(const result of [zero,null]){const r=capacityReader({readContract:async()=>{if(result)return result;throw {name:'ContractFunctionExecutionError',cause:{name:'ContractFunctionRevertedError',reason:'execution reverted: 0x',raw:'0x'}};}},market);assert.equal((await r(host)).enabled,false);}});
test('transport failures retry and invalid addresses do not query RPC',async()=>{const f=fixture(),r=capacityReader(f.pub,market);await assert.rejects(r('bad'),/address/);assert.equal(f.calls.length,0);f.fail();await assert.rejects(r(host),/RPC quota/);f.recover();assert.equal((await r(host)).free,8);});
test('paused and downsized hosts retain active obligations; revoked market has no admission',async()=>{const r=capacityReader({readContract:async c=>({hostCapacity:registry,snapshot:[0,2,0],authorizedMarkets:false})[c.functionName]},market);const x=await r(host);assert.equal(x.active,2);assert.equal(x.free,0);assert.equal(x.authorized,false);});
test('bounded cache expiry refreshes on-chain state',async()=>{const f=fixture();let now=0;const r=capacityReader(f.pub,market,{ttl:5,max:2,now:()=>now});await r(host);now=6;await r(host);assert.equal(f.calls.filter(x=>x==='snapshot').length,2);for(let i=1;i<=4;i++)await r('0x'+String(i).padStart(40,'0'));assert(r.cacheSize()<=2);});
