import test from 'node:test';import assert from 'node:assert/strict';import * as mod from '../frontend/src/core/synchronous-host.js';
test('host requires a cross-tab lock before restoring or handling assignments',async()=>{assert.equal(typeof mod.SynchronousHost,'function');const host=new mod.SynchronousHost({deployment:{verification:{mode:'synchronous-v1'},addresses:{market:'m'},chainId:1},instance:'i',locks:null,chain:{},journal:{}});await assert.rejects(host.start(),/lock/);});
test('restored readiness authorization is never treated as a task or as safe-to-close before nonce consumption',async()=>{
 let nonce=3n;const updates=[];const host=new mod.SynchronousHost({deployment:{verification:{mode:'synchronous-v1'},addresses:{market:'m'},chainId:1},instance:'i',locks:{request:async(_n,_o,fn)=>fn({})},chain:{pending:async()=>({ready:false,taskId:'0x'+'00'.repeat(32),nonce,blockNumber:10n})},journal:{load:async()=>({idle:true,readiness:[{nonce:'3',ready:true}]}),save:async()=>{}},onChange:s=>updates.push(s),ask:async()=>{throw Error('must not pin an idle record')}});
 await host.start();assert.equal(host.session.record,null);assert.equal(updates.at(-1).safeToClose,false);nonce=4n;await host.tick();assert.equal(updates.at(-1).safeToClose,true);host.unlock();
});
test('explicit rearm archives confirmed terminal evidence before admitting a second session',async()=>{
 const archived=[],sent=[],saved=[];const host=new mod.SynchronousHost({deployment:{chainId:1,addresses:{market:'m'}},instance:'i',chain:{hashes:{},pending:async()=>({taskId:'0x'+'00'.repeat(32),nonce:2n,ready:false,blockNumber:20n}),read:async()=> 'hash'},journal:{archive:async r=>archived.push(structuredClone(r)),save:async r=>saved.push(structuredClone(r))},sign:async()=> 'sig',ask:async()=>({}),transport:async(k,p)=>sent.push(k)});
 host.session.record={taskId:'old',manifest:{evidence:'retain'}};host.session.status={phase:'completed',safeToClose:true};host.session.tick=async()=>{};
 await host.readiness(true);assert.equal(archived[0].manifest.evidence,'retain');assert.equal(host.session.record,null);assert.deepEqual(sent,['readiness']);assert.equal(saved.at(-1).idle,true);
});
test('terminal confirmed drain clears the draining indicator',()=>{let status;const host=new mod.SynchronousHost({deployment:{chainId:1,addresses:{market:'m'}},instance:'i',chain:{},journal:{},onChange:s=>status=s});host.draining=true;host.session.update('completed',{safeToClose:true});assert.equal(status.draining,false);});
test('overlapping host polls join one reconciliation instead of racing journal writes',async()=>{let finish,calls=0;const host=new mod.SynchronousHost({deployment:{chainId:1,addresses:{market:'m'}},instance:'i',chain:{},journal:{}});host.session.record={taskId:'t'};host.session.tick=async()=>{calls++;await new Promise(r=>{finish=r})};const a=host.tick(),b=host.tick();assert.equal(calls,1);finish();await Promise.all([a,b]);});
test('a transient first reconciliation failure keeps an initialized recoverable host',async()=>{let failing=true;const host=new mod.SynchronousHost({deployment:{chainId:1,addresses:{market:'m'}},instance:'i',locks:{request:async(_n,_o,fn)=>fn({})},journal:{load:async()=>null},chain:{pending:async()=>{if(failing)throw Error('finality unavailable');return{ready:false,taskId:'0x'+'00'.repeat(32),nonce:0n,blockNumber:1n}}}});await assert.rejects(host.start(),/finality/);assert.equal(host.initialized,true);failing=false;await host.tick();assert.equal(host.session.status.safeToClose,true);host.unlock();});
test('foreign requests during execution are refused rather than leaving bounded reply slots occupied',async()=>{const host=new mod.SynchronousHost({deployment:{chainId:1,addresses:{market:'m'}},instance:'i',chain:{},journal:{}});host.admitting=true;host.admittingTask='t';await assert.rejects(host.assignment({payload:{taskId:'other'}}),/active/);await host.assignment({payload:{taskId:'t'}});});
test('reserved VRF candidate waits without computing or claiming safe closure',async()=>{
 const id='0x'+'33'.repeat(32),host=new mod.SynchronousHost({deployment:{chainId:1,addresses:{market:'m'}},instance:'i',chain:{pending:async()=>({taskId:id,nonce:2n,ready:false,blockNumber:10n,phase:6,admission:{state:1,randomnessDeadline:'30',maxSessionEnd:'200'}})},journal:{},ask:async()=>{throw Error('no execution before allocation');}});
 await host.tick();assert.equal(host.session.status.phase,'awaiting randomness');assert.equal(host.session.status.safeToClose,false);assert.equal(host.session.status.totalDeadline,'200');
});
