import test from 'node:test';import assert from 'node:assert/strict';import * as mod from '../frontend/src/core/synchronous-host.js';
const zero='0x'+'00'.repeat(32),a='0x'+'11'.repeat(32),b='0x'+'22'.repeat(32);
function setup(){const data=new Map(),sent=[],updates=[],states=new Map(),pins=new Set();let p={taskIds:[a,b],tasks:[],nonce:0n,ready:false,blockNumber:10n};const journal=key=>({load:async()=>structuredClone(data.get(key)||null),save:async r=>data.set(key,structuredClone(r)),archive:async r=>{data.set(key+':archive',structuredClone(r));data.delete(key);}});const options={deployment:{chainId:1,addresses:{market:'m'},verification:{mode:'synchronous-vrf-rounds-v1',maxRoundTasks:2}},instance:'i',delegation:{expiry:999n},locks:{request:async(_n,_o,fn)=>fn({})},journal:journal('host'),journalFactory:journal,chain:{pending:async()=>p,snapshot:async r=>({confirmed:true,blockNumber:10n,chainId:1,market:'m',instance:'i',taskId:r.taskId,state:states.get(r.taskId)||1,commitDeadline:30n,revealDeadline:40n,totalDeadline:50n,pendingTask:p.taskIds.includes(r.taskId)?r.taskId:zero,ready:false,readinessNonce:p.nonce}),read:async()=> 'digest',hashes:{result:async()=> 'r',commitment:async()=> 'c',commit:async()=> 'h'}},ask:async(k,x)=>{if(k==='syncPin')pins.add(x.taskId);if(k==='syncRelease')pins.delete(x.taskId);return k==='syncManifest'?{manifest:x.manifest}:k==='syncExecute'?{result:{execDigest:'d',execRoot:'r'}}:{};},resolve:async()=>({mep:{exec:'int-lif'}}),sign:async()=> 'sig',transport:async(k,x)=>sent.push([k,x]),onChange:s=>updates.push(s)};return {options,data,sent,updates,states,pins,setPending:v=>{p={...p,...v}}};}
test('round host independently admits two tasks and retains host drain signatures after per-task archive/restart',async()=>{assert.equal(typeof mod.RoundSynchronousHost,'function');const x=setup(),host=new mod.RoundSynchronousHost(x.options);await host.start();await Promise.all([a,b].map(taskId=>host.assignment({payload:{taskId}})));assert.equal(host.sessions.size,2);assert.deepEqual(new Set(x.sent.filter(([k])=>k==='commit').map(([,p])=>p.taskId)),new Set([a,b]));await host.readiness(false);x.states.set(a,4);x.setPending({taskIds:[b]});await host.tick();assert.equal(host.sessions.size,1);assert.equal(x.data.get('host').readiness.length,1);assert.equal(x.updates.at(-1).safeToClose,false);host.unlock();const restored=new mod.RoundSynchronousHost(x.options);await restored.start();assert.equal(restored.sessions.size,1);assert.equal(restored.draining,true);x.states.set(b,4);x.setPending({taskIds:[]});await restored.tick();assert.equal(x.updates.at(-1).safeToClose,false);x.setPending({nonce:1n});await restored.tick();assert.equal(x.updates.at(-1).safeToClose,true);restored.unlock();});
test('round host continues another task when a dispute responder fails',async()=>{assert.equal(typeof mod.RoundSynchronousHost,'function');const x=setup(),host=new mod.RoundSynchronousHost(x.options);await host.start();await host.assignment({payload:{taskId:a}});await host.assignment({payload:{taskId:b}});host.sessions.get(a).tick=async()=>{throw Error('proof temporarily unavailable')};x.sent.length=0;await assert.rejects(host.tick(),/proof/);assert.ok(x.sent.some(([k,p])=>k==='commit'&&p.taskId===b));assert.equal(x.updates.at(-1).safeToClose,false);host.unlock();});
test('round seals a collecting reservation and signs its task-scoped sealing envelope',async()=>{const x=setup();x.options.deployment.addresses.market='0x'+'33'.repeat(20);x.options.instance='0x'+'44'.repeat(20);x.options.chain.client={getBlockNumber:async()=>12n};x.setPending({taskIds:[a],tasks:[{taskId:a,phase:6,admission:{state:5,closeBlock:'9',randomnessDeadline:'30'}}]});const host=new mod.RoundSynchronousHost(x.options);await host.start();assert.equal(x.sent[0][0],'sealRound');assert.equal(x.sent[0][1].taskId,a);assert.equal(x.sent[0][1].signature,'sig');host.unlock();});
test('restarting durable drain replays the original signature before declaring closure',async()=>{const x=setup();x.setPending({taskIds:[]});x.data.set('host',{version:3,taskIds:[],draining:true,readiness:[{instance:'i',ready:false,nonce:'0',expiry:'100',signature:'original'}]});const host=new mod.RoundSynchronousHost(x.options);await host.start();assert.deepEqual(x.sent[0],['readiness',x.data.get('host').readiness[0]]);assert.equal(x.updates.at(-1).safeToClose,false);host.unlock();});
test('a failed readiness write cannot later publish its in-memory signature during reconciliation',async()=>{const x=setup();x.setPending({taskIds:[],ready:true});const host=new mod.RoundSynchronousHost(x.options);await host.start();let writes=0;x.options.journal.save=async()=>{if(++writes>=2)throw Error('storage offline')};await assert.rejects(host.readiness(false),/storage/);await assert.rejects(host.tick(),/storage/);assert.equal(x.sent.length,0);host.unlock();});
test('restart between task indexing and manifest save can drain after the reservation expires',async()=>{const x=setup();x.setPending({taskIds:[]});x.data.set('host',{version:3,taskIds:[a],draining:true,readiness:[]});const host=new mod.RoundSynchronousHost(x.options);await host.start();assert.equal(x.updates.at(-1).safeToClose,true);assert.equal(host.sessions.size,0);host.unlock();});
test('a repeated healthy assignment is not refused because another task proof is temporarily unavailable',async()=>{const x=setup(),host=new mod.RoundSynchronousHost(x.options);await host.start();await host.assignment({payload:{taskId:a}});await host.assignment({payload:{taskId:b}});host.sessions.get(a).tick=async()=>{throw Error('other task proof unavailable')};await assert.doesNotReject(host.assignment({payload:{taskId:b}}));host.unlock();});
test('unjournaled allocated tasks expire autonomously after finalized commit deadline, including an interrupted manifest save',async()=>{
 for(const indexed of [false,true]){
  const x=setup();x.options.chain.client={getBlockNumber:async()=>31n};
  x.data.set('host',{version:3,taskIds:indexed?[a]:[],draining:true,readiness:[]});
  x.setPending({taskIds:[a],tasks:[{taskId:a,phase:1,commitDeadline:30n,revealDeadline:40n,totalDeadline:50n}],blockNumber:30n});
  const host=new mod.RoundSynchronousHost(x.options);await host.start();assert.equal(x.sent.length,0);assert.equal(x.updates.at(-1).safeToClose,false);
  x.setPending({blockNumber:31n});await host.tick();assert.equal(x.sent.length,1);assert.equal(x.sent[0][0],'finalize');assert.equal(x.sent[0][1].taskId,a);assert.equal(x.updates.at(-1).safeToClose,false);
  x.setPending({taskIds:[],tasks:[]});await host.tick();assert.equal(x.updates.at(-1).safeToClose,true);host.unlock();
 }
});
