import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../frontend/public/node_worker.js',import.meta.url),'utf8').replace(/^import .*;$/gm,'');
function worker(){const handlers=[],events=[];const ctx={Uint8Array,Uint32Array,Map,Set,ArrayBuffer,performance,console,setTimeout,clearTimeout,structuredClone,
 self:{postMessage:m=>events.push(m)},PorwNode:class{},loadKernel:async()=>({}),RelayClient:class{async connect(){return 1}serve(type,id,fn){handlers.push({type,id,fn});return()=>{}}close(){}},
 NodeService:class{constructor(){this.serves=[]}serve(id,o){this.serves.push(o)}stop(){}},FamilyNodeService:class{serve(){throw Error('legacy family service must not start')}stop(){}},FamilyReplayJournal:class{},V:{},decodeHeader:()=>({})};vm.createContext(ctx);vm.runInContext(source+'\n;globalThis.testOps=ops;globalThis.setEvidence=e=>{synchronousExecution=e;synchronousTask=e.taskId;};globalThis.setNode=n=>{node=n;identity={domains:{},delegation:{instance:"host"}}};',ctx);ctx.setNode({models:new Map(),key:{address:new Uint8Array(20)}});return {ctx,handlers,events};}
test('synchronous relay suppresses all legacy result-publishing task handlers',async()=>{const {ctx,handlers}=worker();await ctx.testOps.relay({url:'ws://x',familyMode:true,synchronous:true});assert.equal(handlers.filter(x=>x.type==='task-announce').length,1);let delivered=false;const response=handlers.find(x=>x.type==='task-announce').fn({type:'task-announce',mepId:'m',payload:{taskId:'t'}}).then(r=>{delivered=true;return r;});await Promise.resolve();assert.equal(delivered,false);await ctx.testOps.syncRefuse({taskId:'t',reason:'terminal inconclusive'});const answer=await response;assert.equal(answer.type,'result-refused');assert.equal(answer.payload.execRoot,undefined);});
test('worker refuses close while synchronous evidence is pinned',async()=>{const {ctx}=worker();assert.equal(typeof ctx.testOps.syncPin,'function');await ctx.testOps.syncPin({taskId:'t'});await assert.rejects(ctx.testOps.close(),/pending/);await assert.rejects(ctx.testOps.syncPin({taskId:'other'}),/active/);});
test('proof responder refuses a different task and returns only the pending phase move',async()=>{const {ctx}=worker();assert.equal(typeof ctx.testOps.syncProof,'function');await assert.rejects(ctx.testOps.syncProof({taskId:'unknown',state:{phase:0}}),/evidence/);});
test('real WASM execution retains roots, row witnesses and restart material through verification',async()=>{
 const H=await import('./harness.mjs');const [{PorwNode},{loadKernelFromBytes},{synthesizePayloadV2},V,L,{NodeService},{FamilyNodeService},delta,model]=await Promise.all(['node.js','porw.js','synth.js','verify.js','lif.js','node_service.js','family_service.js','delta.js','model.js'].map(H.porw));
 const wasm=fs.readFileSync(H.porwDir+'/sketch.wasm'),payload=synthesizePayloadV2('sync',32,128),identity={privHex:H.KEYS[1]};
 const node=new PorwNode(await loadKernelFromBytes(wasm),identity);const st=await node.loadModel('sync',payload,{maxSteps:4,exec:'lif'});st.family=true;
 const exec=await node.execute(st.mep.mepId,{steps:4,commitStride:2,stimulusSeed:7});const taskId='0x'+'19'.repeat(32),hex=H.hex;
 const manifest={taskId,baseMepId:hex(st.mep.mepId),mep:{mepId:hex(st.mep.mepId),modelId:hex(st.modelId),enrollmentMepId:hex(st.mep.mepId),exec:'int-lif',neurons:32,synapses:128},payload:{taskId,steps:4,commitStride:2,stimulusSeed:7,initStateRoot:hex(exec.result.initStateRoot)},ancestors:[]};
 const context={Uint8Array,Uint32Array,Map,Set,ArrayBuffer,BigInt,performance,console,setTimeout,clearTimeout,structuredClone,self:{postMessage(){}},PorwNode,NodeService,FamilyNodeService,V,L,...delta,...model,loadKernel:()=>loadKernelFromBytes(wasm)};
 vm.createContext(context);vm.runInContext(source+'\n;globalThis.opsForTest=ops;globalThis.setTestNode=(n,i)=>{node=n;identity=i;synchronousExecution=null;synchronousTask=null;};',context);context.setTestNode(node,identity);
 const ops=context.opsForTest,{manifest:durable}=await ops.syncManifest({manifest});assert.ok(durable.baseBytes.length);
 const {result}=await ops.syncExecute({taskId,manifest:durable});assert.equal(result.execRoot,hex(exec.result.execRoot));
 const roots=await ops.syncProof({taskId,state:{phase:0,party:{revealed:false}}});assert.equal(roots.move.functionName,'revealRoots');assert.deepEqual(Array.from(roots.move.args[1]),exec.result.actRoots.map(hex));
 const refine=await ops.syncProof({taskId,state:{phase:1,lifParty:{refined:false},lif:{seg:0}}});assert.deepEqual(Array.from(refine.move.args[1]),(await node.lifSegmentRoots(st.mep.mepId,0)).roots.map(hex));
 const row=await ops.syncProof({taskId,state:{phase:3,step:1,neuron:1,lifParty:{rowPosted:false}}});assert.equal(row.move.functionName,'postRowLif');
 await assert.rejects(ops.close(),/pending/);
 context.setTestNode(new PorwNode(await loadKernelFromBytes(wasm),identity),identity);
 const restored=await ops.syncExecute({taskId,manifest:durable,expectedResult:result});assert.equal(restored.result.execRoot,result.execRoot);
 const resumedRoots=await ops.syncProof({taskId,state:{phase:0,party:{revealed:false}}});assert.deepEqual(Array.from(resumedRoots.move.args[1]),exec.result.actRoots.map(hex));
 await ops.syncPublish({taskId,signature:'synchronous-original-signature',confirmedReveal:true});
});
test('publishing output requires explicit confirmed reveal authorization',async()=>{const {ctx}=worker();assert.equal(typeof ctx.testOps.syncPublish,'function');await assert.rejects(ctx.testOps.syncPublish({taskId:'unknown',signature:'sig'}),/confirmed/);});

test('zero-input row proof opens only row bounds and previous self, never a nonexistent CSR term',async()=>{const {ctx}=worker(),z=new Uint8Array(32),state={v:0,g:0,refr:0,flags:0,count:0},node={models:new Map([['0x'+'00'.repeat(32),{csr:{chunk:256,csrTree:{root:z},rowTree:{root:z}}}]]),lifPartialSums:async()=>({k0:128,sums:[]}),lifOpenState:async()=>({state,proof:[]}),openRowStart:()=>({value:128,proof:[]}),openCsrChunk:()=>{throw Error('no CSR record exists')}};ctx.setEvidence({taskId:'t',node,mepId:z,manifest:{payload:{}}});const result=await ctx.testOps.syncProof({taskId:'t',state:{phase:3,step:1,neuron:31,lifParty:{rowPosted:true,sums:[]},otherLifParty:{rowPosted:true,sums:[]}}});assert.equal(result.move.functionName,'proveSynapseTermLif');assert.equal(result.move.args[1][4][1],'0x');});
test('large rows resume bounded uploads from the confirmed row prefix',async()=>{const {ctx}=worker(),z=new Uint8Array(32),state={v:0,g:0,refr:0,flags:0,count:0},node={models:new Map([['0x'+'00'.repeat(32),{}]]),lifPartialSums:async()=>({k0:0,sums:Array.from({length:1500},(_,i)=>BigInt(i))}),lifOpenState:async()=>({state,proof:[]})};ctx.setEvidence({taskId:'t',node,mepId:z,manifest:{payload:{}}});const result=await ctx.testOps.syncProof({taskId:'t',state:{phase:3,step:1,neuron:2,lifParty:{rowPosted:false,sums:Array(1024).fill(0n)}}});assert.equal(result.move.functionName,'postRowLifChunk');assert.equal(result.move.args[1],1024);assert.equal(result.move.args[2],1500);assert.equal(result.move.args.at(-1).length,476);});
