#!/usr/bin/env bash
# Deploy the mesh with BNB parameters and save the addresses as environment variables (never in git).
#   NETWORK=bsc-testnet PK=0x... ./deploy.sh [extra forge args]
#   NETWORK: opbnb-testnet (5611) | bsc-testnet (97) | opbnb (204) | bsc (56) | anvil (31337)
# Output: .env.<network> (gitignored, chmod 600) with PORW_* variables — the contract addresses AND the deployer
# address/private key (PORW_DEPLOYER, PORW_DEPLOYER_KEY: it owns the registries) — `source` it before the relayer.
set -euo pipefail
cd "$(dirname "$0")"
case "${NETWORK:-anvil}" in
  opbnb-testnet) RPC="${RPC:-https://opbnb-testnet-rpc.bnbchain.org}"; CHAIN=5611 ;;
  bsc-testnet)   RPC="${RPC:-https://bsc-testnet-rpc.publicnode.com}"; CHAIN=97 ;;  # 443 endpoint; the official :8545 one is blocked by some egress proxies
  opbnb)         RPC="${RPC:-https://opbnb-mainnet-rpc.bnbchain.org}"; CHAIN=204 ;;
  bsc)           RPC="${RPC:-https://bsc-dataseed.bnbchain.org}"; CHAIN=56 ;;
  anvil)         RPC="${RPC:-http://127.0.0.1:8545}"; CHAIN=31337; PK="${PK:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}" ;;
  *) echo "unknown NETWORK"; exit 2 ;;
esac
: "${PK:?set PK (deployer private key)}"
NET="${NETWORK:-anvil}"
# block-time-dependent parameters: DESIGN.md §4 assumes ~1 s blocks; override EPOCH_BLOCKS etc. via env for BSC (0.75 s) or others
(cd contracts && forge script script/DeployBNB.s.sol --rpc-url "$RPC" --chain-id "$CHAIN" --private-key "$PK" --broadcast "$@")
# the script wrote deployments/<chainId>.json (gitignored); turn it into an env file (gitignored) and print it
J="deployments/$CHAIN.json"; [ -f "$J" ] || { echo "missing $J"; exit 1; }
ENVF=".env.$NET"
node -e '
const fs = require("fs"); const [j, envf, rpc, net, pk] = process.argv.slice(1); const d = JSON.parse(fs.readFileSync(j, "utf8")); const a = d.addresses;
const { privateKeyToAccount } = require("viem/accounts"); const deployer = privateKeyToAccount(pk).address;
const lines = [`# aigg-bnb deployment on ${net} (chain ${d.chainId}) — generated by deploy.sh, keep out of git`, `PORW_NETWORK=${net}`, `PORW_CHAIN_ID=${d.chainId}`, `PORW_RPC=${rpc}`, `PORW_EPOCH_BLOCKS=${d.epochBlocks}`,
  `PORW_VERIFIER=${a.verifier}`, `PORW_MEP_REGISTRY=${a.meps}`, `PORW_INSTANCES=${a.instances}`, `PORW_BEACON=${a.beacon}`, `PORW_CLAIMS=${a.claims}`, `PORW_MARKET=${a.market}`, `PORW_DISPUTES=${a.disputes}`, `PORW_RELAYS=${a.relays}`, `PORW_WHITELIST=${a.whitelist}`,
  `PORW_DEPLOYER=${deployer}`, `PORW_DEPLOYER_KEY=${pk}`];
fs.writeFileSync(envf, lines.join("\n") + "\n", { mode: 0o600 }); console.log(lines.filter((l) => !l.startsWith("PORW_DEPLOYER_KEY")).join("\n") + "\nPORW_DEPLOYER_KEY=<saved, not printed>");
' "$J" "$ENVF" "$RPC" "$NET" "$PK"
echo; echo "saved to $ENVF (chmod 600, gitignored; contains the deployer key). Next: add PORW_RELAYER_KEY and PORW_MEP_IDS to it, then: source $ENVF && npm run relayer"
